### ISSUE TITLE
Figure out how to handle Python in venv for delegated tasks

### ISSUE THREAD

**Issue by bjschafer** [bjschafer/ansible-printing#16]
Right now, the version check in the `fluidd` role relies on the `github3` Python module. To avoid clutter on target Pis, the module is installed on the host running Ansible.

However, it seems that when running a task with `delegate_to: localhost`, Ansible finds the system default Python interpreter and not the one in the venv that it was invoked with.

For now, the workaround is to add a block like this in `inventory.yaml`:

```yaml
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /path/to/your/venv/bin/python3
```

...and then run with `ansible-playbook test-playbook.yaml --limit '!localhost'`.
